function y = constellation_permute(x,idx)
% CONSTELLATION_PERMUTE  Apply one of the 6 standard cross-ratio orderings.
% idx is 1..6 for each row.
% Usage: y = constellation_permute(x,idx)
a = [1 2]; b = [3 4]; c = [5 6]; d = [7 8];
perm = [a b c d;...
        a c b d;...
        a d b c;...
        a b d c;...
        a c d b;...
        a d c b];
col = perm(sub2ind(size(perm),repmat(idx(:),1,8),repmat(1:8,numel(idx),1)));
row = repmat((1:numel(idx)).',1,8);
y = x(sub2ind(size(x),row,col));
end
