function q = a2q(A)
% A2Q  Attitude matrix to quaternion.
% Uses the stable trace/diagonal branch formula and returns [qx;qy;qz;qw].
% Usage: q = a2q(A)
tr = trace(A);
if tr>=0
    s = 2*sqrt(1+tr);
    q = [(A(2,3)-A(3,2))/s;...
         (A(3,1)-A(1,3))/s;...
         (A(1,2)-A(2,1))/s;...
         s/4];
else
    [~,k] = max(diag(A));
    switch k
        case 1
            s = 2*sqrt(1 + A(1,1) - A(2,2) - A(3,3));
            q = [s/4;...
                 (A(1,2)+A(2,1))/s;...
                 (A(1,3)+A(3,1))/s;...
                 (A(2,3)-A(3,2))/s];
        case 2
            s = 2*sqrt(1 - A(1,1) + A(2,2) - A(3,3));
            q = [(A(1,2)+A(2,1))/s;...
                 s/4;...
                 (A(2,3)+A(3,2))/s;...
                 (A(3,1)-A(1,3))/s];
        otherwise
            s = 2*sqrt(1 - A(1,1) - A(2,2) + A(3,3));
            q = [(A(1,3)+A(3,1))/s;...
                 (A(2,3)+A(3,2))/s;...
                 s/4;...
                 (A(1,2)-A(2,1))/s];
    end
end
q = q./(sign_nz(q(4))*norm(q));
end
